services:
  backend:
    build:
      context: ./backend
    container_name: hello-backend
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8000/health"]
      interval: 10s
      timeout: 3s
      retries: 10

  frontend:
    build:
      context: ./frontend
    container_name: hello-frontend
    ports:
      - "4200:80" # nginx s≈Çucha na 80 w kontenerze
    depends_on:
      backend:
        condition: service_healthy

  frontend-dev:
    image: node:20-alpine
    container_name: hello-frontend-dev
    working_dir: /app
    ports:
      - "4300:4200"
    environment:
      CHOKIDAR_USEPOLLING: "true"   # stabilniejsze watch na Windows
      NG_CLI_ANALYTICS: "false"
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
    command: ["sh","-lc","set -e; npm install --no-fund --no-audit && npx ng serve --host 0.0.0.0 --port 4200 --proxy-config proxy.conf.json"]

    depends_on:
      backend:
        condition: service_healthy

volumes:
  node_modules:

networks:
  default:
    name: hello-stack