services:
  
  backend:
    profiles: ["dev","prod"]
    build:
      context: ./backend
    container_name: hello-backend
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8000/health"]
      interval: 10s
      timeout: 3s
      retries: 10

  frontend:
    profiles: ["prod"]
    build:
      context: ./frontend
    container_name: hello-frontend
    ports:
      - "4200:80" # nginx w kontenerze s≈Çucha na 80
    depends_on:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost/ | grep -qi '<!doctype html>'"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 10s

  frontend-dev:
    profiles: ["dev"]
    image: node:20-alpine
    container_name: hello-frontend-dev
    working_dir: /app
    ports:
      - "4300:4200"   # dev przez ng serve
    environment:
      CHOKIDAR_USEPOLLING: "true"
      NG_CLI_ANALYTICS: "false"
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
    command:
      - sh
      - -lc
      - |
        set -e
        npm install --no-fund --no-audit
        npm run start
    depends_on:
      - backend

volumes:
  node_modules:

networks:
  default:
    name: hello-stack


